name: GNU Autotools and Dependencies
on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{format('{0}:{1}:{2}', github.repository, github.ref, github.workflow)}}
  cancel-in-progress: true

jobs:
  GNU-platform:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: set up GNU auto tools
      run: |
        sudo apt-get install -qq -y   autotools-dev 
        sudo apt-get install -qq -y   autoconf
        sudo apt-get install -qq -y   libtool

    - name: set up dependencies
      run: |
        sudo apt-get install  -qq -y  libcurl4-openssl-dev
        sudo apt-get install  -qq -y  libssl-dev
        sudo apt-get install  -qq -y  libpam-dev
        sudo apt-get install  -qq -y  libqrencode-dev
        sudo apt-get install  -qq -y  make

    - name: test autotools
      run: |
        autoconf -V
        automake --version