name: GNU Autotools and Dependencies
on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{format('{0}:{1}:{2}', github.repository, github.ref, github.workflow)}}
  cancel-in-progress: true

jobs:
  GNU-platform:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: set up GNU auto tools
      run: |
        apt-get install -qq  autotools-dev 
        apt-get install -qq  autoconf
        apt-get install -qq  libtool

    - name: set up dependencies
      run: |
        apt-get install  -qq libcurl4-openssl-dev
        apt-get install  -qq libssl-dev
        apt-get install  -qq libpam-dev
        apt-get install  -qq libqrencode-dev
        apt-get install  -qq make

    - name: test autotools
      run: |
        autoconf -V
        automake --version